name: issue-notify

on:
  issues:
    types: [opened,assigned,closed,reopened]
  issue_comment:
    types: [created]
  pull_request:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  create:

env:
  IRC_REPO_OWNER: 'EntropyOrg'

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: PDLPorters/devops/github-actions/irc-notifications@master
        with:
          target-notifications: true
          repository_owner: ${{ env.IRC_REPO_OWNER }}
